### ISSUE TITLE
Windows: you need to wrap path in quotes

### ISSUE THREAD

**Issue by vankasteelj** [j-holub/Node-MPV#18]
I encountered issues with the module when trying to spawn MPV from `C:\Program Files`. At first I thought it was some kind of permission issue, Windows being weird with it's Program Files folder, but it turns out it was way dumber: the spaces in the path made the entire thing go south. 

I'll PR a fix that shouldn't change anything for linux/osx, but make it more solid on Windows

**Comment by j-holub** [comment]
Thanks for pointing that out. I using Mac and Linux for 6 years now, so I've really no idea about Windows development. Gonna look at those PRs and merge them.

**Comment by vankasteelj** [comment]
lol, I called mpv 'vlc' on c38bb07 commit message.

**Comment by j-holub** [comment]
Yes I noticed that :D

**Comment by vankasteelj** [comment]
I can rebase if you want :)

**Comment by j-holub** [comment]
I don't mind too much, but if you'd like to, sure, go for it ^^

**Comment by vankasteelj** [comment]
i've been using the modified v2 for a day, and it's working as it should, fyi

**Comment by j-holub** [comment]
Glad to hear that. I was thinking about adding a little more error handling when starting the player in the **reject** part of the promise and then publishing it.

**Comment by vankasteelj** [comment]
I did notice something strange, if I pass by mistake for example `mpv.loadFile({filename: 'this.mkv', path:'foo/bar'}) ` it just fails without warning me of anything

**Comment by vankasteelj** [comment]
And was also wondering why you used require('promise') instead of standard Promise(), almost every nodejs version has it by now

**Comment by vankasteelj** [comment]
and I think I also need something like `mpv.on('seek', newPosition)` but I can wrap something around with timeposition tracking

**Comment by j-holub** [comment]
The synthax for loadFile is just

```
mpv.loadFile('path/to/this.mpv');
```

Why it fails without any message? Hmm I have a guess. The function takes a second parameter called `mode` , you can see its effect in the mpv documentation:

<img width="683" alt="bildschirmfoto 2017-08-06 um 15 57 25" src="https://user-images.githubusercontent.com/19982919/29003929-0419dee4-7ac0-11e7-8ecd-c92442f8e316.png">

I assume that it takes `this.mkv` as the path, and `foo/bar`as the mode, sends that to mpv and the error happens there.

But yes I should definitely add more error handling on that part.

As for the promise thing. Yeah I wasn't too familiar with promises at that time, I'll have a look into it. The fewer dependencies the better, thanks.

**Comment by vankasteelj** [comment]
I can PR replacing the promise module, it shouldn't take more than a few min

**Comment by j-holub** [comment]
The seek thing seems like a great idea actually. I will have to look into mpv's API to see how one could accomplish that though.

Sure if you want to :)
