### ISSUE TITLE
Windows errors

### ISSUE THREAD

**Issue by vankasteelj** [j-holub/Node-MPV#28]
Hi, 

I encountered an error on windows with your latest v2. 

Two things from my debugging:

1) lib/util.js has a typo on line 105: `returnreject` needs a space (also, returning is not necessary here as you don't have code it can do after the reject)

2) lib/mpv/_startStop.js : for a reason (paths always have been a mystery to me), on line 35, you need to remove the enclosing `"` from the this.options.binary, otherwise it throws a ENOENT error

**Comment by j-holub** [comment]
Hey there,

thanks a lot. Don't know how that typo happened. And yes, I don't really get pathes on Windows either, but I'm glad someone as actually testing/using this module on Windows, really helps :)
