### ISSUE TITLE
cycleAudioTracks includes empty audio track

### ISSUE THREAD

**Issue by zmartell** [j-holub/Node-MPV#36]
Hi,

Is there a way to make cycleAudioTracks skip the "none" audio track mpv creates?

**Comment by j-holub** [comment]
Hey there,

I'm afraid I need some more information about this. What do you mean when you say "the none audio track mpv creates"?

**Comment by j-holub** [comment]
Closing because I didn't receive any more information. Feel free to reopen this issue if you have more information on what's wrong :)
