### ISSUE TITLE
Allow user to supply path to the mpv binary

### ISSUE THREAD

**Issue by notpushkin** [j-holub/Node-MPV#5]
In case it's not in the PATH (i. e. bundled with the applicaion).

**Comment by j-holub** [comment]
That's a good suggestion thank you. I added it with version 0.12.0.

Sorry the other issue is not progressing as quickly, it's a little complicated for me and Final Fantasy XV has just been released ;) But I'm still working on it!

Cheers!

Edit: Thank you very much for using my API by the way :)
