### ISSUE TITLE
Deprecate support for mpv below 0.17 ?

### ISSUE THREAD

**Issue by AxelTerizaki** [j-holub/Node-MPV#52]
Hello.

I'm currently working on #33 (I'll submit a PR if I'm happy and if it works :p) because I'm going to need something like that for our project, and while looking through the code, I was wondering if it was still a good thing to support mpv below 0.17 in 2018. 

It could remove a lot of code in the module, hence why I'm asking. No problem if you think it's still useful :)

**Comment by wopian** [comment]
mpv 0.14 is the newest version available in Ubuntu 16.04's repositories and other distros are similarly outdated on releases.

**Comment by AxelTerizaki** [comment]
Does that mean node-mpv has to support an outdated version? Most people who want to use mpv will install the newest version and not their distro's, IMHO.

**Comment by j-holub** [comment]
Ubuntu is as far as I know the most common linux distribution and just calling `apt-get install mpv` is usually the easiest way to install something, especially for beginners.

It's not really a big deal to support the older version, it's especially easy to just leave the option to pass the old command line argument to start an ipc server.

What do you think could be removed, the only relevant thing is the `findIPCCommand` method in **util.js** . I would opt to support older versions as long as it doesn't cause a major pain in the butt which it does not so far in my opinion.

**Comment by AxelTerizaki** [comment]
Alright, sounds fair :)

I was just opening the issue to discuss it, if you think it's fine, then it is, we can close it.
