### ISSUE TITLE
[Question] how to use the loadPlaylist() api?

### ISSUE THREAD

**Issue by sir-kain** [j-holub/Node-MPV#56]
The definition of this function is `loadPlaylist (playlist, mode="replace")`

I need to know the type of the "playlist" parameter

**Comment by AxelTerizaki** [comment]
If I follow [the code here](https://github.com/00SteinsGate00/Node-MPV/blob/Node-MPV-2/lib/mpv/_playlist.js#L21) `playlist` is a playlist file. You should check mpv's manual to see what kind of playlist file it expects.

**Comment by sir-kain** [comment]
Awesome it works with filepath as the "playlist" parameter like 
`await mpv.loadPlaylist("src/ply.txt");`

`src/ply.txt` is my file with list of streams
```
https://cdns-preview-5.dzcdn.net/stream/c-50543900d3d62a3eb5882407d66acd71-5.mp3
https://cdns-preview-d.dzcdn.net/stream/c-d28ee67c24d60e740866c7709d772f55-10.mp3
```

**Comment by j-holub** [comment]
It seems as if everything's fine here and I can close this issue, right?
