### ISSUE TITLE
loop method in lib/mpv/_controls.js

### ISSUE THREAD

**Issue by f00a04b4f13eec8a254e44cd529d4c88** [j-holub/Node-MPV#6]
The setProperty call within the loop method is missing the first argument which should be the string "loop". It can be seen here: https://github.com/00SteinsGate00/Node-MPV/blob/c04a3761821ec9476ec1ba7e30a03ddc47ea6856/lib/mpv/_controls.js#L45

I appreciate the work you have done to make this useful utility.

Keep it up,
f00a04b4f13eec8a254e44cd529d4c88

**Comment by j-holub** [comment]
Thank you very much for noticing and pointing it out so clearly.
I have fixed it with the **0.12.1** release.

Cheers,

Jan
