### ISSUE TITLE
Changing the statuschange behaviour to single messages per change

### ISSUE THREAD

**Issue by j-holub** [j-holub/Node-MPV#69]
Hey guys,

in #68 @hedgehog90 proposed another status change event, that he called `statuschange_single`, that triggers a message about a single status change whenever one happens.

At the moment there's this big status change object that looks something like this, just populated with even more properties

```JSON
{
  "mute": false,
  "duration": 320,
   "media-title": "somesong"
}
```
and if there's a change to one single of those properties, the `statuschange` event returns the whole object, which could possibly have like 50 properties.

Instead of introducing `statuschange_single` I'm rather leaning towards replacing the old one with the new behaviour, that would return something like this

```JSON
{
   "property": "duration",
   "value": 400
}
```
Of course, this would break the API. But since we're doing a Version 2 here anyways, which means breaking the API is kind of okay, since people migrating from Version 1 to Version 2 will have to migrate their code anyways.

What do you guys think? @vankasteelj , @AxelTerizaki and @hedgehog90. You guys seem to be the most active user of this package.

**Comment by AxelTerizaki** [comment]
The idea is that when anything changes, that event is triggered, right? I don't see any particular problem with that. It does change app code though as we now have to test which property got changed.

I don't mind the change. I haven't been following the whole discussion which led to it though, but I don't see any particular issue with it (apart from a slight code change)

**Comment by j-holub** [comment]
Yes exactly, if property A changed (and was observerd of course), there will be a `statuschange`event for property A.

**Comment by twilson90** [comment]
I don't see why we can't just retain the original statuschange event and have an extra event for singular property changes, as I've proposed.
It would avoid any problems with back-compatibility.

Also, I can imagine being confused by the change in behaviour when the name of the event is the same.

**Comment by AxelTerizaki** [comment]
Jan's switching to a new major version, so introducing a breaking change isn't that bad as long as it's documented in a migration guide of sorts.

I mostly prefer one way to achieve things than multiple ones as having multiple ways can get confusing sometimes, add to the code base, adds to the documentation, etc.

Simpler is better :)

**Comment by j-holub** [comment]
It's definitely possible @hedgehog90 , but it's pretty much for the reasons @AxelTerizaki stated, simple is better and having multiple ways of doing stuff just adds a layer of confusion.

There already is a migration guide, so it's just adding the changes to that.

## Big Statusobject

### Pros

  * Everything in one place, helps people to see properties they didn't know existed
  * If an app keeps track of the properties, updating could be as easy as
    ```JavaScript
        mpv.on('statuschange', (statusobj) => {
            state = statusobj;
       });
    ```

### Cons

  * Even if only a single property changes, the whole object is sent. The user of the library has to check if every single property did change or not, by keeping track of the state and comparing it with the new state every time

## Individual Messages

### Pros

  * an event relevant to a certain property is only fired when that property did actually change
  * seems like it would keep the logic cleaner, for example it could look like this
    ```JavaScript
        mpv.on('statuschange', (prop, value) => {
            switch(prop) {
                case "duration":
                    // code
                    break;
            }
        });
    ```
  * possiblity to add more information to a single property, for example
    ```JSON
        {
            "property": "duration",
            "value": 300,
            "timestamp": "<unix timestamp of the change>",
            "somethingelse": "foo"
        }
    ```

### Cons

   * API change
   * not every observed property in one place


Anything you guys want to add?

One possibility I see is using a rename to keep the old behaviour with a warning, that it is deprecated. By that I mean, for example, the new event would be called `state` or `status` or something. Then I see if I can add a message to an event, that it's deprecated and remove it from the documentation (not yet from the code). This gives people time to transition.

**Comment by twilson90** [comment]
I'm in 2 minds about it now as well!
I'll let you decide whether to keep it as statuschange or to rename it, it's not a huge issue either way.

Also, good idea with the timestamp property.

**Comment by j-holub** [comment]
I implemented this and removed the old behaviour. I think it's better now, allthough it breaks the module. While doing so I also changed the way observing properties works, it no longer requires IDs by the user
