### ISSUE TITLE
loop-playlist

### ISSUE THREAD

**Issue by jordicasals** [j-holub/Node-MPV#75]
Hi,

would it be possible to add the "loop-playlist" function?

Thank you very much!

**Comment by j-holub** [comment]
Hey :) 

yes it's possible and not much work at all actually, thank you for the suggestion. I will add it asap.

In the meantime you can use `player.setProperty('loop-playlist', 'inf')` to achieve the same effect. Or replace  `inf` with an integer, if you want to have the playlist looped only a certain number of times. Calling `player.setProperty('loop-playlist', 'no')` will stop looping the playlist.

Cheers!

**Comment by jordicasals** [comment]
Thank you very much!

I did not remember I was able to do it using the setProperty method. This
is perfect



El dl., 20 abr. 2020, 16.51, Jan Holub <notifications@github.com> va
escriure:

**Comment by j-holub** [comment]
I added a `loopPlaylist()` and a `clearLoopPlaylist()` method to Version 1 of the package and published it. The API is fitting to how the Methods in Version 1 look, however I'm not really happy about it yet, so I have not yet implemented anything for Version 2 yet. If you happen to use Version 2 (which you should, it's much better than Version 1), please continue using the `setProperty()`w way in the meantime.

**Comment by jordicasals** [comment]
Hi,

I've implemented the software with the setProperty method and it works
perfectly. Thank you.

Anyway, as I am using the version 2, I will wait for future updates.

Best regards,



El dt., 21 abr. 2020, 21.33, Jan Holub <notifications@github.com> va
escriure:
