### ISSUE TITLE
Make MPV top-level

### ISSUE THREAD

**Issue by vankasteelj** [j-holub/Node-MPV#76]
Hi, is there a way to make MPV be on top again? I see in the docs there is a '--ontop', but I cannot seem to use that to control MPV and make it go "on top of" my JS app

**Comment by NiaMori** [comment]
mpv documentation mentions
> Most options can be set as runtime via properties as well. Just remove the leading -- from the option name.

So you can use `setProperty` to change an option at runtime.

```js
await mpv.setProperty('ontop', true)
```

It will makes your mpv window stay on top.

**Comment by j-holub** [comment]
Thanks @Ancokey for the answer. Can you confirm that this works and does what you need @vankasteelj ?

**Comment by vankasteelj** [comment]
Yes, followed by a ontop false. Thank you!

```js
mpv.setProperty('ontop', true)
mpv.setProperty('ontop', false)
```

This pops MPV back on top of everything without breaking anything
