### ISSUE TITLE
Other Protocols av://

### ISSUE THREAD

**Issue by oliveirapedroma** [j-holub/Node-MPV#86]
Hi!

Is it possible to use other protocols than file or http with node-mpv? For example av:// to use with image/sound capture hardware? Ex. av://dshow:video="FHD Webcamera"

Protocols: [https://mpv.io/manual/stable/#protocols](https://mpv.io/manual/stable/#protocols)

Thank you!

**Comment by j-holub** [comment]
Hey!

sorry for the super late response. To be honest I don't know, I think the code in this module just passes the URL onward to MPV so in theory it should be possible? Have you tried?

If it's not possible it should be an easy fix and we/I can work on that. Just let me know.

**Comment by j-holub** [comment]
I just took a look, I actually check for "https" in the input, I didn't know of any other protocols at that time. So now, right now it's not possible to use other protocols, but that shouldn't be a problem, it should be an easy fix. What's the easiest way for me to test if this works?

https://github.com/j-holub/Node-MPV/blob/86bc0cb302d04fcef6e2877995618840077134bd/lib/mpv/mpv.js#L100

**Comment by oliveirapedroma** [comment]
Hi Jan!

Thank you for your reply! The easiest way is to test with a webcam by passing the URL av://v4l2:/dev/video0 in a Linux environment or av://dshow:video="FHD Webcamera" in a Windows environment, where FHD Webcamera is the name of the device that is present on windows device manager

Thank you

**Comment by j-holub** [comment]
> The easiest way is to test with a webcam by passing the URL av://v4l2:/dev/video0 in a Linux environment or av://dshow:video="FHD Webcamera" in a Windows environment, where FHD Webcamera is the name of the device that is present on windows device manager

You mentioned exactly the 2 OSes I don't have access to haha :D but no worries, Webcam is a great tip actually, should be one Google search to find what I gotto enter for macOS. Thanks! : )

**Comment by j-holub** [comment]
I was going to work on this right now, but it seems, on macOS it's not that easy to access the webcam with mpv (I remember using it with OpenCV years ago, which worked without a problem), there's no `/dev/video0` on macOS and I don't really know what to input.

If I made a PR with some code that I think might solve the issue, would you be able to test and verify it?

**Comment by oliveirapedroma** [comment]
Of course, feel free to create a PR and I will test it.

Thank you

**Comment by j-holub** [comment]
I have just created a PR for this (#87), please have a look whenever you have some time to spare.

**Comment by j-holub** [comment]
Implemented with #87
