### ISSUE TITLE
udp:// and other URLS

### ISSUE THREAD

**Issue by NolanCassidy** [j-holub/Node-MPV#90]
#### Bug Description
I stream using UDP. The Node-MPV worked but this one does now.  The code thinks it is a file.

#### How To Reproduce
.load(udp://localhost:1234)

#### Expected behavior
Should open up a stream

##### Software Versions
     - Node-Mpv: Which version are you using? 2
 - MPV: newest
 - OS: Which OS are you using? Windows 10

**Comment by NolanCassidy** [comment]
https://github.com/j-holub/Node-MPV/pull/91

Solution is here and ready to be merged.

**Comment by j-holub** [comment]
Thanks a lot : )
